adverbs = [
    ['hardly', 14],
    ['accidently', 15],
    ['sadly', 25],
    ['funnily', 28],
    ['hopefully', 29],
    ['immediately', 30],
    ['randomly', 25],
    ['silently', 30],
    ['arbitarily', 32],
    ['weirdly', 32],
    ['mistakenly', 33],
    ['periodically', 33],
    ['grossly', 35],
    ['suddenly', 35],
    ['happily', 40],
    ['massively', 40],
    ['ruthlessly', 45],
    ['urgently', 50],
    ['sneakily', 52],
    ['quickly', 55],
    ['angrily', 60],
    ['viciously', 60],
    ['epicly', 70],
]

verbs = [
    ['totally fails at', 0],
    ['screws thyself while slapping', 3],
    ['fails at', 5],
    ['fails a bit at', 8],
    ['misses', 10],
    ['trolls', 10],
    ['wobbles', 15],
    ['splashes', 16],
    ['faps', 18],
    ['clubs', 20],
    ['punches', 24],
    ['dangles', 25],
    ['kicks', 25],
    ['debugs', 30],
    ['stamps', 30],
    ['cuffs', 33],
    ['combats', 38],
    ['hits', 39],
    ['blunts', 40],
    ['brats', 40],
    ['blats', 45],
    ['tackles', 45],
    ['cuts', 50],
    ['dissects', 50],
    ['screws', 50],
    ['slaps', 50],
    ['bangs', 55],
    ['battles', 55],
    ['double slaps', 55],
    ['triple slaps', 58],
    ['blanches', 59],
    ['disconnects', 60],
    ['stomps on', 60],
    ['punishes', 66],
    ['kills', 70],
    ['eliminates', 71],
    ['damages', 75],
    ['eleminates', 79],
    ['disables', 80],
    ['destroys', 90],
    ['naruto-runs', 84],
]


adjectives = [
    ['a gay', 15],
    ['a tiny', 15],
    ['a very small', 20],
    ['a disgusting', 25],
    ['a rotten', 25],
    ['a wonderful', 25],
    ['a drooling', 27],
    ['a sharp', 29],
    ['a hot', 30],
    ['a small', 30],
    ['a wild', 30],
    ['the frist', 30],
    ['a suspicous', 31],
    ['an electric', 33],
    ['a bloody', 35],
    ['a funny', 35],
    ['a gross', 35],
    ['a poison', 35],
    ['a living', 37],
    ['a sexy', 15],
    ['a', 40],
    ['a flying', 40],
    ['a mysterious', 40],
    ['an amazing', 40],
    ['an awesome', 40],
    ['a grim', 50],
    ['a large', 50],
    ['the first', 50],
    ['the one and only', 55],
    ['a huge', 60],
    ['an unbelievable', 62],
    ['a dangerous', 65],
    ['a monster', 65],
    ['a hellish', 66],
    ['an unholy', 66],
    ['a sexy', 69],
    ['an enormous', 70],
    ['a giant', 80],
    ['an epic', 80],
    ['an evil', 95],
    ['an invisible', 25],
    ['a crazy', 35],
    ['a fascinating', 31],
    ['a tasty', 16],
    ['a bloody', 25],
]

items = [
    ['banana peel', 25],
    ['railgun', 75],
    ['vacuum cleaner', 35],
    ['trout', 25],
    ['monitor', 35],
    ['vacuum', 10],
    ['mouse', 13],
    ['used quote', 11],
    ['chainsaw', 60],
    ['rusty chainsaw', 65],
    ['book', 13],
    ['dictionary', 15],
    ['lightsabre', 78],
    ['toilet paper roll', 18],
    ['WC brush', 15],
    ['big fucking gun', 75],
    ['gravity gun', 65],
    ['frag grenade', 52],
    ['toy', 24],
    ['Deep Blue Computer', 36],
    ['garden gnome', 16],
    ['C64 home computer', 22],
    ['Amiga multimedia computer', 23],
    ['P5 microprocessor', 11],
    ['hadron collider', 50],
    ['hammer', 32],
    ['smithhammer', 38],
    ['pneumatic drill', 35],
    ['screwdriver', 24],
    ['mini elevator', 14],
    ['nunchaku', 45],
    ['ZX Spectrum home computer', 21],
    ['closet', 27],
    ['dandi', 19],
    ['gremlin', 23],
    ['dildo', 18],
    ['jar', 19],
    ['black hole', 96],
    ['space station', 74],
    ['comet', 54],
    ['doll', 23],
    ['tape', 17],
    ['strawberry', 12],
    ['sausage', 13],
    ['blog', 17],
    ['ninja', 51],
    ['steak', 20],
    ['sphere of healing', -20],
    ['mashup', 12],
    ['popcorn bucket', 18],
    ['dictionary', 22],
    ['google translation', 17],
    ['eel', 19],
    ['shark', 37],
    ['iron', 25],
    ['skull', 18],
    ['deer', 22],
    ['painting', 15],
    ['rainbow', 12],
    ['pot of gold', 23],
    ['grim', 50],
    ['duck', 15],
    ['XBOX', 20],
    ['PS3', 19],
    ['PS4', 21],
    ['PS5', 23],
    ['XBox', 22],
    ['unicorn', 35],
    ['toilet paper roll', 13],
    ['flamethrower', 45],
    ['sabretooth', 21],
    ['CPU', 13],
    ['edge', 22],
    ['drone strike', 55],
    ['horse', 42],
    ['cactus', 33],
    ['puppy', 12],
    ['boar', 29],
    ['parrot', 27],
    ['link', 21],
    ['savoy', 24],
    ['pumpkin', 27],
    ['sandwich', 22],
    ['wrench', 33],
    ['email', 10],
    ['bone', 13],
    ['hummingbird', 11],
    ['backup', 10],
    ['toilet', 39],
    ['tarball', 14],
    ['g-zip', 11],
    ['lighter', 18],
    ['beamer', 42],
    ['dongle', 17],
    ['flying spagetthi monster', 15],
    ['cake', 19],
    ['hillbilly', 42],
    ['frying pan', 39],
    ['blow up doll', 19],
    ['cartridge', 30],
    ['wafflecone', 16],
    ['sushi', 15],
    ['squirrel', 25],
    ['cat', 30],
    ['whip', 40],
    ['printer', 35],
    ['version control system', 15],
]
